### ISSUE TITLE
Implementovat event: Dan Juan

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/levy-sluchat#10]
Dan může randit i s Beatrice i s Flavií zároveň. Když ho pak vezmeš s oběma někam, tak se na něj naserou, a s tebou a mezi sebou se jim ten relationship zlepší, a Dan na tebe taky bude naštvaný.

- [ ] Dan může randit s Beatrice
- [ ] Dan může randit s Flavií - (Eternal Couple)
- [ ] Může se to zvrhnout

**Comment by IAmWave** [comment]
hotovka
