### ISSUE TITLE
Implementovat event: Alex

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/levy-sluchat#11]
Alex může randit buď s Beatrice nebo s Cecilem. S Cecilem se dají dohromady sami od sebe, s Beatrice je musíš poslat do baru, aby se opili. Pokud už chodí s Cecilem, tak se rozejdou když se vyspí s Beatrice, a je to all around awkward. Relationship s Beatrice se rozpadne po nějaký době (Povaha Beatrice, viz spodek Postavy.txt).

- [x] Alex může randit s Cecilem
- [x] Alex může randit s Beatrice
- [x] může se to rozpadnout infidelitou
- [x] může se to rozpadnout časem

**Comment by IAmWave** [comment]
(udělám zítra)
