### ISSUE TITLE
Indikátory toho, jak moc se mají lidi rádi

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/levy-sluchat#12]
#7  - Dalo by se to zobrazovat různě barevnýma čárama mezi lidma v main screenu?

**Comment by zouharvi** [comment]
Aktuálně to koresponduje k tomu, že tam existuje tag. To by bylo třeba vybrainit zdali vůbec dokážeme z těch tagů dostat informaci "X má rád Y"

**Comment by IAmWave** [comment]
Teďka dělám na tom, že každý vztah bude mít ještě skalární hodnotu toho, jak se mají rádi, od 0 do 10. Pak to bude (snad) brnkačka

**Comment by IAmWave** [comment]
Hotovo. Dal bych šedou čáru pro neutrál, a pak zelenou/červenou na ty strany
