### ISSUE TITLE
Průběžně snižovat vztahy s You

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#26]
Měl by se snižovat fondness, pro lidi se kterýma člověk ven nejde, a zvýšit pokud s nima někam jdeš (až na situace kdy se jim to nelíbilo, ale to bych udělal tak že v tom případě odečteme od fondness dostatečně, abychom tohle obecný "přebili")

**Comment by petrroll** [comment]
Udelám na to situaci.
