### ISSUE TITLE
Systém sympatií

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#29]
Vztahy `like` a `dislike` ovlivňující jak se změní fondness když člověk pošle dva lidi spolu

**Comment by petrroll** [comment]
connected: https://github.com/allemansratten/levy-sluchat/issues/28

**Comment by petrroll** [comment]
Skrze meta akce, co se provedou vždy a přidají / odeberou tagy? Problém na interference "tag ovlivní fondness" :: "fondness ovlivní tag"

**Comment by IAmWave** [comment]
teď jsem tam commitnul nějaký řešení

**Comment by IAmWave** [comment]
a teď jsem ho i pushnul :)))))))
