### ISSUE TITLE
Ať se nedávají dohromady pokud je přítomen lover

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#31]
Pokud AB maji crush a AC spolu chodi a pozvu ven ABC, AB spolu zacnou taky chodit (protoze se kontroluje nepritomnost crushe, ale ne lovera)

**Comment by petrroll** [comment]
Fixed, pls test @IAmWave .

**Comment by petrroll** [comment]
Bylo to bugged, už j to fixed a tested.
