### ISSUE TITLE
Pokud nějaký tag nebyl odstaněn, nevypisovat odpovídající zprávu

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#33]
Momentálně se ukáže že na tebe všichni přestali mít crush (protože fondness klesl), i když ho nikdy neměli

**Comment by petrroll** [comment]
Fixnu já.

**Comment by petrroll** [comment]
Nově se do doneEffects dávají jen added/removed tagy, který udělaly změnu.
