### ISSUE TITLE
Když triggeruješ moc eventů zároveň, tak se to nevejde na screen

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/levy-sluchat#34]
T1: D+B kamkoliv
T2: D+F kamkoliv
T3: všichni na bowling 
To udělá tolik textu, že se to nevejde na screen

**Comment by petrroll** [comment]
![image](https://user-images.githubusercontent.com/1764721/79700691-f593d400-8297-11ea-8ced-b49123123ff6.png)
