### ISSUE TITLE
Tutorial/instrukce

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#37]
Bylo by fajn mít i ve hře a nejen na LD stránkách, for posterity. Klidně i samostatná stránka s krátkým textem v HTML.

**Comment by zouharvi** [comment]
Mohli bychom to dát přímo na stránku, anebo do hry při načítání (ono pokud se to bude načítat online, tak to bude lidem chvilku trvat). Ale jsem spíše proti tomu. Připadá mi, že hlavní merit je opravdu v exploration.
