### ISSUE TITLE
Šipky v grafu dávat od prostředků ikonek

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#38]
Momentálně jdou všechny z jednoho místa. IMO by bylo hezčí, kdyby to vycházelo "z postavy". Bylo by potřeba pak ty čáry udělat o něco kratší.

Matematicky můžeme dát ten poloměr stejný jako ve kterém je ta postava, a pak to zkrátit. Spočítáme vynormovaný vektor směru od A do B, a posuneme endpointy odpovídajícím směrem o tolik, kolik je potřeba (poloměr ikonky + padding)

**Comment by petrroll** [comment]
Není prostě jednodušší tu čáru dát od osoby, a dát jí v z-indexu pod avatar?

**Comment by petrroll** [comment]
Případně `z` stack: čára, kruh, avatar. Kruh udělá místo okolo avataru.

**Comment by zouharvi** [comment]
> Není prostě jednodušší tu čáru dát od osoby, a dát jí v z-indexu pod avatar?
Ne, protože avatar je průhledný.
