### ISSUE TITLE
Barva mírného like zelená místo šedé

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#39]
Předtím jsem myslel že kdyby to bylo těch defaultních 5, tak tam bude šedá, ale asi je pravda že nedávat tam nic je rozumnější. Pak ale pozitivní už by měla být zelená.

**Comment by petrroll** [comment]
On už není default 5? :O

**Comment by zouharvi** [comment]
No ne. Ono i pokud spolu nemají fondness, ale mají tag, tak se tam musí vykreslit _nějaká_ čára. A pokud je default, tak šedá.

**Comment by IAmWave** [comment]
Myslel jsem to tak, že když má někdo fondness 7 (default třeba mezi B a E) tak je to světle šedé, ale chceme, aby to vypadalo jako pozitivní vztah, takže bych tam dal světle zelenou.

**Comment by zouharvi** [comment]
Ale to tak je. 7-8 je 0x70cc78, 9-10 je 00de13.

**Comment by IAmWave** [comment]
Ahh jasně. Já jsem myslel, že crushes mají nastavený ten fondness na víc, my bad
