### ISSUE TITLE
Ať jde prohrát (aspoň pro testování)

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/levy-sluchat#44]
Pro playtestování by bylo dobré aspoň třeba někde nahoře napsat, že jsme v situaci, kdy někdo má vůči nám minimální možný fondness (`MIN_FONDNESS`, teď 0), takže jsme "prohráli". To se bude hodit ať už budeme mít postupné odcházení lidí nebo ne. Nepotřebujeme nutně "game over screen" hned teď.

**Comment by petrroll** [comment]
Will do.

**Comment by zouharvi** [comment]
Will do too.
