### ISSUE TITLE
Vymyslet Failstate

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/levy-sluchat#7]
Chtělo by to vymyslet jak hráč prohraje a vymyslet pro to nějaký zobrazování

**Comment by IAmWave** [comment]
mít nějaký tagy na to jak moc tě mají lidi rádi, a skončit když tě někdo hodně nemá rád

případně pokud se nějací dva lidi hodně nemají rádi, ale to možná zamezuje tomu jak moc spicy situace můžou vzniknout

**Comment by IAmWave** [comment]
Na tohle se klidně podívám, asi přidám prostě pět úrovní toho jak moc tě někdo má rád a to budu průběžně upravovat

**Comment by zouharvi** [comment]
Možná chceme prostě zamezit tomu, aby se kdokoliv z přátel z té sítě odtrhl? Takže třeba že se s někým bude mega nesnášet, anebo nebude mít rád nikoho?

**Comment by petrroll** [comment]
Mizení lidí 
- [ ] přidat gone tag
- [ ] neukazovat gone lidi na mapě, nejde naně kliknout, nekreslí se k nim čáry
- [ ] filtrovat zprávy zahrnující gone lidi (sanity check)

**Comment by zouharvi** [comment]
Fondness na MIN_FONDNESS.
